// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppState = {
  auth: AuthState | null;
  settings: SettingsState;
  github: GithubSettings;
  issueCount: number;
  reviews: Array<PullRequest>;
  availableOrgs: Array<Organization>;
  theme: Theme;
};

export type AuthState = { token: string | null; hostname: string | null; user: Author | null };

export type AuthTokenOptions = { hostname: string; token: string };

export type Author = { login: string; avatarUrl: string; url: string };

export type GithubSettings = { archive: boolean; type: string; state: string };

export type Label = { name: string; color: string };

export type Labels = Array<Label>;

export type Organization = { value: string; label: string };

export type PullRequest = {
  title: string;
  url: string;
  number: bigint;
  repository: string;
  author: Author;
  createdAt: string;
  closed: boolean;
  isDraft: boolean;
  reviewDecision: string;
  totalCommentsCount: bigint;
  isReadByViewer: boolean;
  labels: Labels;
  statusCheckRollup: StatusCheckRollup;
};

export type Review = {
  repository: string;
  author: Author;
  createdAt: string;
  number: bigint;
  url: string;
  title: string;
  closed: boolean;
  isDraft: boolean;
  reviewDecision: string;
  totalCommentsCount: number;
  labels: Labels;
  statusCheckRollup: StatusCheckRollup;
  isReadByViewer: boolean;
};

export type SettingsState = { openAtStartup: boolean; isCompactMode: boolean; fetchInterval: number };

export type StateChangePayload = { newState: AppState; changedFields: Array<StateField> };

export type StateField = 'auth' | 'settings' | 'github' | 'issueCount' | 'reviews' | 'availableOrgs' | 'theme';

export type StatusCheckRollup = { state: string };

export type Theme = 'dark' | 'light';

export type User = {
  login: string;
  name: string | null;
  id: number;
  avatar_url: string;
  html_url: string | null;
  company: string | null;
  email: string | null;
};

export type UserId = bigint;
