// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppState = {
  auth: AuthState | null;
  settings: SettingsState | null;
  github: GithubSettings | null;
  issueCount: number;
  reviews: Array<Review>;
  availableOrgs: Array<Organization>;
  theme: Theme;
};

export type AuthState = { token: string | null; hostname: string | null; user: Author | null };

export type AuthTokenOptions = { hostname: string; token: string };

export type Author = {
  login: string;
  id: UserId;
  node_id: string;
  avatar_url: string;
  gravatar_id: string;
  url: string;
  html_url: string;
  followers_url: string;
  following_url: string;
  gists_url: string;
  starred_url: string;
  subscriptions_url: string;
  organizations_url: string;
  repos_url: string;
  events_url: string;
  received_events_url: string;
  type: string;
  site_admin: boolean;
  patch_url: string | null;
  email: string | null;
};

export type GithubSettings = { archive: boolean; type: string; state: string };

export type Organization = { value: string; label: string };

export type Review = {
  repository: string;
  author: string;
  author_object: Author;
  created_at: string;
  number: bigint;
  url: string;
  title: string;
  closed: boolean;
  is_draft: boolean;
  review_decision: string;
  total_comments_count: number;
};

export type SettingsState = { openAtStartup: boolean; isCompactMode: boolean; fetchInterval: number };

export type StateChangePayload = { newState: AppState; changedFields: Array<StateField> };

export type StateField = 'auth' | 'settings' | 'github' | 'issueCount' | 'reviews' | 'availableOrgs' | 'theme';

export type Theme = 'dark' | 'light';

export type User = {
  login: string;
  name: string | null;
  id: number;
  avatar_url: string;
  html_url: string | null;
  company: string | null;
  email: string | null;
};

export type UserId = bigint;
